name: brilliance
description: "Glue Brilliance flow design"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  window_manager: ^0.4.3
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.3.1
  hugeicons: ^0.0.7
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  # 文件选择组件
  # file_selector: ^1.0.3
  shared_preferences: ^2.3.2
  # Json编辑器
  flutter_code_editor: ^0.3.2
  flutter_highlight: ^0.7.0
  json5: ^0.8.2
  path_provider: ^2.1.4
  highlight: ^0.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/app_icon_256.png
  fonts:
    - family: dingtalk
      fonts:
        - asset: assets/fonts/DingTalk-JinBuTi.ttf